version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always

  api:
    image: SI_180410_api
    restart: unless-stopped
    depends_on:
      - rabbitmq
    ports:
    - "180410:80"
      
  generator:
    image: SI_180410_generator
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - "180405:80"

  frontend:
    image: SI_180410_frontend
    restart: always
    ports:
      - "180297:8000"
