version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
     context: ./
     dockerfile: ./Dockerfile.API
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - mongo
    ports:
    - "8080:80"
      
  generator:
    build:
      context: ./
      dockerfile: ./Dockerfile.Generator
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - "8083:80"

  # frontend:
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile.Frontend
  #   restart: always
  #   ports:
  #     - "8000:8000"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/